name: uniarrival
recipe: drupal8

config:
  via: apache
  xdebug: false
  config:
    php: .lando/php.ini

services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    run_as_root:
      - /app/.lando/adminer.sh
    portforward: true
  appserver:
    type: 'php:7.2'
    webroot: web
    build:
      - composer install
    overrides:
      environment:
        WKV_SITE_ENV: lando
        HASH_SALT: notsosecurehash
  database:
    type: 'mariadb:10.1'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    globals:
      gulp-cli: latest
      bower: latest
    build:
      - /app/.lando/node.sh

tooling:
  bower:
    service: node
  gulp:
    service: node
  node:
    service: node
  npm:
    service: node
  production:
    description: Build production package.
    cmd:
      - appserver: /app/.lando/production.sh
  syncdb:
    description: Synchronise local database with production.
    cmd:
      - appserver: /app/.lando/syncdb.sh
  update:
    description: Update local database.
    cmd:
      - appserver: /app/.lando/update.sh
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root

proxy:
  mailhog:
    - mail-uniarrival.lndo.site
  adminer:
    - adminer-uniarrival.lndo.site

# events:
#   post-db-import:
#     - appserver: cd $LANDO_WEBROOT && drush @local cr -y && drush @local uli

# Lando version.
version: v3.0.0-rc.23
