<?php

/**
 * Implements hook_mail().
 */
function angapp_mail($key, &$message, $params) {

  switch ($key) {

    case 'results':

      // Prepare subject and body.
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = 'Your Uni Arrival Advisor Steps';

      $step = 1;
      $previous_header = "";

      foreach ($params['intro'] as $row) {
        $message['body'][] = $row['title'];
        $message['body'][] = strip_tags($row['body']);
      }

      $message['body'][] = '----------------';

      foreach ($params['progress'] as $row) {
        $message['body'][] = strip_tags($row['question']) . ': ' . ($row['answer']);
      }

      $message['body'][] = '----------------';

      foreach ($params['nodes'] as $row) {
        if (in_array($row['nid'], $params['hidden'])) {
          continue;
        }
        if ($previous_header != $row['header']) {
          $message['body'][] = "Step " . $step++ . ":";
          $previous_header = $row['header'];
        }
        $message['body'][] = strip_tags($row['answer']);
      }

      $message['body'][] = '----------------';

      foreach ($params['disclaimer'] as $row) {
        $message['body'][] = $row['title'];
        $message['body'][] = strip_tags($row['body']);
      }

      break;
  }
}
