<?php

use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_mail().
 */
function angapp_mail($key, &$message, $params) {

  switch ($key) {

    case 'results':

      // Prepare subject and body.
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = 'Your Uni Arrival Advisor Steps';
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';

      $step = 1;
      $previous_header = "";
      $separator = '<br/>';

      foreach ($params['intro'] as $row) {
        $message['body'][] = $row['title'];
        $message['body'][] = $row['body'];
      }

      $message['body'][] = $separator;

      $list = '<ul>';
      foreach ($params['progress'] as $row) {
        $list .= '<li>' . SafeMarkup::checkPlain($row['question'] . ': ' . ($row['answer'])) . '</li>';
      }
      $list .= '</ul>';
      $message['body'][] = $list;

      $message['body'][] = $separator;

      foreach ($params['nodes'] as $row) {
        if (in_array($row['nid'], $params['hidden'])) {
          continue;
        }
        if ($previous_header != $row['header']) {
          $message['body'][] = "Step " . $step++ . ":";
          $previous_header = $row['header'];
        }
        $message['body'][] = $row['answer'];
      }

      $message['body'][] = $separator;

      foreach ($params['disclaimer'] as $row) {
        $message['body'][] = $row['title'];
        $message['body'][] = $row['body'];
      }

      $message['body'] = [SafeMarkup::checkPlain(implode($message['body']))];

      break;
  }
}


/**
 * Implements hook_mail_alter().
 */
function angapp_mail_alter(&$message) {

}
